# -*- coding: utf-8 -*-
"""readme.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Xixc53JWUoiL5fZs69ItKdreIxelj_S

## Project Summary

**Title**: Credit Score Classification using EDA  
**Objective**: To explore customer data from Paisabazaar and classify individuals into `Good`, `Standard`, or `Poor` credit score categories. This helps in automating credit decisions and detecting potential fraud.

### Dataset
- 100,000 rows, 28 features
- Target variable: `Credit_Score`
- Features: Income, EMI, Payment Behavior, Credit Mix, Inquiries, etc.

### Methods Used
- Data Cleaning (no missing values)
- Label Encoding for categorical variables
- Visualization: Histograms, Boxplots, Correlation Matrix
- Analysis: Univariate, Bivariate, Multivariate

### Insights
- High income & low EMI → Good score
- Many credit inquiries & late payments → Poor score
- Features like Credit Mix & Outstanding Debt were predictive

### Business Impact
- Faster loan approvals
- Early fraud detection
- Better credit risk evaluation
"""